version: '3.8'
services:
  nginx:
    #直接拿 nginx official image 來使用 
    image: library/nginx:1.19-alpine
    container_name: "charlie_nginx"
    ports:
      - 8787:80
    volumes:
      - "/home/ec2-user/web1/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "/home/ec2-user/web1/project:/var/www/html"
    links:
      - db
  php:
    #PHP 常常要設定執行環境或其他 extensions ，另外 build image 使用
    image: "charlie_php"
    build: /home/ec2-user/web1/php
    container_name: "charlie_php"
    ports:
      - 9000:9000
    volumes:
      - "/home/ec2-user/web1/project:/var/www/html"
    links:
      - db
  db:
   image: mysql:5.7
   ports:
     - 3306:3306
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: project
